(ns language.enus)

(def lines
  {;25 Jul 2021
   "Organization Account" "Company Account"
   ;"Username" "Nome do Usuário"
   ;"Password" "Senha"
   "Your password is saved!"  "Your password has been saved."
   "Remember me" "Remember me"
   "Sign In" "Log in"
   "Please enter organization account"   "Please enter your account name."
   "Plase enter account information" "Plase enter account information."

   ;27 Jun 2021
   "Amount" "Account"
   "Phone number must contain 7 to 11 digits." "Phone number must contain from 7 to 11 digits."

   ;29 Apr 2021
   "Currency" "Currency"
   "Unknown Number" "Unknown Number"
   
   ;settings
  "General Settings" "General Settings"
   "Brand Name" "Company Name"
   "Your company / brand name" "Your company/brand's name"
   "Company invoice name" "Name on Invoices"
   "Tax Authority" "Tax Authority"
   "Tax Number" "Tax Number"
   "Invoice Address" "Address on Invoices"
   "E-mail" "Email"
   "City" "Region"
   "Town" "City"
   "Company Location" "Company Location"
   "Phones" "Phone Numbers"
   "Order Status" "Accept Orders"
   "Open" "Yes"
   "Kapalı" "No"
   "Customer Phones" "Customers' Phones"
   "Hidden" "Hidden"
   "Visible" "Visible"
   "Sendind SMS" "Sendind SMS"
   "IVR Type" "IVR Type"
   "Not available" "Not Available"
   "Repeating order" "Repeating Order"
   "Product amount" "Product Amount"
   "Language" "Language"
   "Other Settings" "Other Settings"
   "User Accounts" "User Accounts"
   "Delivery Zones" "Delivery Zones"
   "Brand Settings" "Brand Settings"
   "API Settings" "API Settings"
   "Telsam Settings" "Telsam Settings"
   "SMS Contents" "SMS Contents"
   ;settings.cljs/delivery areas
   "Zone Name" "Zone Name"
   "All Subscribers" "All Subscribers"
   "Red Zone" "Red Zone"
   "Blue Zone" "Blue Zone"
   "Yellow Zone" "Yellow Zone"
   "Zone" "Zone"
   "Add" "Add"
   ;"Delete" "Sil"
   "All accounts without assigned delivery area will be automatically assigned to the first one." "All accounts without assigned delivery area will be automatically assigned to the first one."

   ;Right Column
   "Workload" "Workload"
   "Today's orders" "Today's Orders"
   "Scheduled" "Scheduled"
   "Overdue" "Overdue"
   "Completed" "Completed"
   "User: " "User: "

   ;Navbar
   ;"User: " "Kullanıcı: "
   "Restart the app" "Restart the App"
   "Secure log-out" "Secure Logout"
   "Operation" "Live Screen"
   "New Account" "New Account"
   "Account" "Account"
   "Accounts" "Accounts"
   "All Accounts" "All Accounts"
   "Inventory" "Inventory"
   "Storages" "Storages"
   "Products" "Products"
   "Carriers" "Carriers"
   "Invoice" "Invoice"
   "Accountancy" "Accountancy"
   "Make a payment" "Make a Payment"
   "Get a payment" "Get a Payment"
   "Reports" "Reports"

   ;smartbox
   "Search" "Search"
   "New Order" "New Order"
   
   ;order
   "Unassigned" "Unassigned"
   "Debit" "Debit" 
   "Credit" "Credit"
   "Filters" "Filters"
   "My orders" "My Orders"
   "Unassigned orders" "Unassigned Orders"
   "Hide delivered" "Hide completed orders."
   "Show delviered" "Show completed orders."
   "Details" "Details"
   ;"Products" "Ürünler"
   "Carrier" "Carrier"
   ;...
   ;"Account" "Abone"
   "Schedule order" "Schedule Order"
   "Now" "Now"
   "Order note" "Comment"
   "Addition/Discount" "Service Fee/Discount"
   "Total: " "Total: "
   "Save" "Save"
   "Close" "Close"

   ;employee status
   "delivering" "delivering"
   "on-duty" "on-buty"
   "break" "break"
   "offline" "offline"

   ;Accounts
   "Please provide a name" "Please provide a name."
   "Wrong location format" "Wrong location format."
   "Please provide a phone number" "Please provide a phone number."
   "Phone number must be 10 digits" "Phone number must contain 10 digits."
   "Account Name" "Account Name"
   "Tax ID" "Tax ID"
   ;"Tax Authority" "Vergi Dairesi"
   ;"Invoice Address" "Fatura Adresi"
   "Account ID" "Account ID"
   "It will be assigned automatically" "It will be assigned automatically."
   "IMPORTANT: Please don't use this area without consulting us." "IMPORTANT: Please don't use this area without consulting us."
   "If you leave empty a number will be assigned"  "If you leave it empty, a number will be assigned."
   "Name & Surname or Business Name" "Name & Surname or Business Name"
   "Note (Displays next to the name)" "Note (displayed next to the name)"
   "Receipt or Invoice" "Receipt or Invoice"
   "Receipt" "Receipt"
   ;"Invoice" "Fatura"
   "IVR Orders" "IVR Orders"
   "If this is closed, the user cannot place order via IVR." "If this is closed, the user cannot place orders via IVR."
   ;"Open" "Açık"
   "Closed" "Closed"
   "Delivery Area" "Delivery Area"
   "Neighbourhood" "Neighbourhood"
   "Street Name" "Street Name"
   "Building" "Building"
   "Address Details" "Address Details"
   "Sales Promotions" "Sales Promotions"
   "Apply" "Apply"
   "Don't Apply" "Don't Apply"
   "Special Discounts" "Special Discounts"
   "Delivery Location" "Delivery Location"
   ;"Phones" "Telefonlar"
   "Lent Equipment" "Rented Equipment"
   "Notes" "Notes"
   "Archived" "Archived"
   "Yes" "Yes"
   "No" "No"
   "Invoice Information" "Invoice Information"
   "Bank Account" "Bank Account"
   "The record has been archived!" "The record has been archived."
   "Successfully saved!" "Successfully saved."
   "Save another record" "Save another record."
   ;"Save" "Kaydet"
   ;"New Account" "Yeni Hesap"
   ;"Account:" "Hesap"

      ; ---customertable.cljs
   "Paid back to the customer" "Paid back to the customer."
   "Customer paid towards debt" "Customer paid towards debt."
   "Debtors" "Debtors"
   "Creditors" "Creditors"
   ;"Lent Equipment" "Emanet Alanlar"
   "Active Accounts" "Active Accounts"
   "Archived Accounts" "Archived Accounts"
   ;"Account" "Abone"
   "Latest Order" "Latest Order"
   "Address" "Address"
   ;"Notes" "Notlar"
   "Export" "Export"

  ;Employee.cljs
   "Plase enter a name" "Plase enter a name."
   "Minimum 3 characters" "Minimum 3 characters."
   "Carrier Name & Surname" "Carrier's Name and Surname"
   "Phone" "Phone"
   "Color" "Color"
   "Status" "Status"
   "Assigned to Storage" "Assigned to Storage"
   "New Carrier" "New Carrier"
   "Carrier:"  "Carrier:"
   "Quick ledger record" "Quick Ledger Record"

   ;Inventory.cljs
   "Item Name" "Item Name"
   ;"Details" "Detaylar"
   "Item Code" "Item Code"
   "Auto-assignment" "Auto-assignment"
   "If you leave it empty a number will be assigned" "If you leave it empty, a number will be assigned."
   ;"Color" "Renk"
   "Track Returnables" "Track Returnables"
   "If you want to track returnables choose 'Yes'. Once it's chosen it can't be changed later!" "If you want to track returnable items, choose 'Yes'. This cannot be changed later."
   "Sellable Item" "Sellable Item"
   "Nonsellable items can be tracked. Customers can't see them." "Nonsalable items can be tracked. Customers can't see them."
   "Price with VAT" "Price With Tax"
   "VAT" "Tax"
   "Price without VAT" "Price Without Tax"
   "Returnable" "Returnable"
   "New Item" "New Item"
   "Item" "Item"

   ;Search 
   "Order History" "Order History"
   ;"Make a payment" "Ödeme yap"
   ;"Get a payment" "Ödeme al"
   "Edit" "Edit"
   ;Order history


   ;Order pop-up
   "Balance»customer" "Balance»customer"
   "Scheduled Delivery" "Scheduled Delivery"
   "Notes»order" "Comment»order"
   ;"Products" "Ürünler"
   "Service Fee" "Service Fee"
   "Discount" "Discount"
   "Order ID" "Order ID"
   ;"Carrier" "Plasiyer"
   ;"Unassigned" "Belirlenmedi"
   "This order is assigned to someone else." "This order is assigned to someone else."

   "I have delivered the items" "I have delivered the items."
   "I have collected containers" "I have collected containers."
   "I have collected the payment" "I have collected the payment."
   "Not enough products in the storage" "Not enough products in the storage."
   "Payer" "Payer"
   "Payee" "Payee"

   ;Next two lines will be recorded to storage history 
   "Order delivery" "Order Delivery"
   "Collected containers" "Collected Containers"

   "Payment Amount" "Payment Amount"
   "Items have been delivered" "Items have been delivered."
   "Containers have been collected"    "Containers have been collected."
   "Payment has been collected" "Payment has been collected."

   "Cash Account" "Cash Account"

   "Changed»order" "Changed»order"
   "Completed orders cannot be changed." "Completed orders cannot be changed."
   "Save Changes" "Save Changes"

   "Total" "Total"
   "Total Price" "Total Price"

   ;phone & mixed.cljs
   "Call via IVR" "Call via IVR"
   "Call" "Call"
   "Calling..." "Calling..."
   "Delete Record" "Delete Record"
   "Delete" "Delete"
   "Cancel Deletion" "Cancel Deletion"
   "Wrong format" "Wrong Format"

   ;Warehouse.cljs
   ;"Plase enter a name" "İsim girilmelidir"
   ;"Color" "Renk"
   ;"Notes" "Notlar"
   ;"Save" "Kaydet"
   ;"Notes" "Notlar"
   ;"Target Storage" "Hedef Depo"
   ;"Notes" "Notlar"
   ;"Save" "Kaydet"
   "Storage Name" "Storage Name"
   "Storage Type" "Storage Type"
   "Vehicle" "Vehicle"
   "Warehouse" "Warehouse"
   "Storage Manager" "Storage Manager"
   "Source Storage" "Source Storage"
   "Target Storage" "Target Storage"
   "Source" "Source"
   "Target" "Target"
   "Items" "Items"
   "Add New Storage" "Add New Storage"
   "Add Items" "Add Items"
   "Move Items" "Move Items"
   "Remove Items" "Remove Items"
   "Move items to another storage" "Move items to another storage."
   "Storage" "Storage"
   "Move" "Move"

   ;Ledger.cljs
   ;"Source" "Kaynak"
   ;"Target" "Hedef"
   ;"Save" "Kaydet"
   "Saved" "Saved"
   "This area is mandatory" "This area is mandatory."
   "Please select" "Please select."
   "Enter the value" "Enter the value."
   "Add a transaction" "Add a transaction."
   "Transaction reference" "Transaction Reference"
   "Transaction date" "Transaction Date"
   ;"Now" "Şimdi"
   "Value" "Value"
   "Date" "Date"
   ;"Account" "Hesap"
   "Start date" "Start Date"
   "End date" "End Date"
   ;"Apply" "Uygula"
   "Transaction" "Transaction"
   "Transaction Filter" "Transaction Filter"
   "Past 5 weeks" "Past 5 weeks"
   "Filtered transactions" "Filtered Transactions"
   "New Transaction" "New Transaction"


   ;users.cljs
   ;"Carrier" "Plasiyer"
   "Username" "Username"
   "Password" "Password"
   "Manager" "Manager"
   "Name" "Name"
   "User" "User"
   "Permissions" "Permissions"
   "Add a new account" "Add a new account."

   ;Time.cljs
   "January" "January"
   "February" "February"
   "March" "March"
   "April" "April"
   "May " "May"
   "June" "June"
   "July" "July"
   "August" "August"
   "September" "September"
   "October" "October"
   "November" "November"
   "December" "December"

   "Jan" "Jan"
   "Feb" "Feb"
   "Mar" "Mar"
   "Apr" "Apr"
   "May" "May"
   "Jun" "Jun"
   "Jul" "Jul"
   "Agu" "Aug"
   "Sep" "Sep"
   "Oct" "Oct"
   "Nov" "Nov"
   "Dec" "Dec"

   "Monday" "Monday"
   "Tuesday" "Tuesday"
   "Wednesday" "Wednesday"
   "Thursday" "Thursday"
   "Friday" "Friday"
   "Saturday" "Saturday"
   "Sunday" "Sunday"

   "minutes" "minutes"
   "hours" "hours"
   "days" "days"
   "months" "months"
   "ago" "ago" 
   "later" "later"})

; END OF THE FILE
; Ignore everthing after this point

(def blocks
  {:settings-top
   [:<>
    [:h4 "Önemli Not:"]
    [:p "Türkçe içerik" [:strong " datanız kaybolur."] " Dropbox ile bağlanın"]
    [:p "Şunu kullanıyoruz " [:a {:href "https://remotestorage.io/"} "remotestorage.io"] " protokolle bağlanın."]]})
